[package]
name = "mmd"
version = "0.1.0"
description = "An implementation of PMD/PMX/VMD used in MMD (MikuMikuDance)."
authors = ["aoowweenn <aoowweenn@gmail.com>"]

[dependencies]
nom = "^2.1"
byteorder = "^1"
encoding = "^0.2"
